services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "6500:5432"  
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./app.env
    
  pgAdmin:
    image: elestio/pgadmin:REL-8_12
    container_name: pgAdmin
    env_file:
      - ./app.env
    ports:
      - "5050:8081"
    depends_on:
      - postgres

volumes:
  postgresDB: