version: '3.8'

services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    volumes:
      - ./db/migration:/migrations
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migration:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://root:secret@db:5432/simple_bank?sslmode=disable",
      "up"
    ]
    depends_on:
      database:
        condition: service_healthy

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
      - migrate
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: simple_bank