services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    volumes:
      - ./db/migration:/migrations
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h database -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin4:
    image: elestio/pgadmin:REL-8_12
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ha@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 8081
    ports:
      - "8081:8081"
    volumes:
      - ./servers.json:/pgadmin4/servers.json

 # Migrate database at startup
  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migration:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://myuser:secret@database:5432/simple_bank?sslmode=disable",
      "up"
    ]
    depends_on:
      database:
        condition: service_healthy

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
      - migrate
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: secret
      DB_NAME: simple_bank